language: python
python:
  - "3.7"
matrix:
  include:
    - os: linux
      dist: xenial
    - language: generic
      os: osx
      before_install:
        - brew update
        - brew upgrade python
        - virtualenv env -p python3
        - source env/bin/activate
install:
  - pip install tox
script:
  - tox
before_deploy:
  - pip install pipenv
  - pipenv install
  - pipenv install -d
  - pipenv run pyinstaller main.spec
  - tar -C dist/mocker -cvzf mocker-${TRAVIS_TAG}-${TRAVIS_OS_NAME}.tar.gz .
deploy:
  provider: releases
  api_key: ${GH_TOKEN}
  file: "mocker-${TRAVIS_TAG}-${TRAVIS_OS_NAME}.tar.gz"
  skip_cleanup: true
  on:
    tags: true
