language: python
python:
  - "3.6"
install:
  - pip install tox
script:
  - tox
before_deploy:
  - pip install pipenv
  - pipenv install
  - pipenv install -d
  - pipenv run pyinstaller main.spec
  - tar cvzf mocker.tar.gz dist/mocker/*
deploy:
  provider: releases
  api_key: ${GH_TOKEN}
  file: "./mocker.tar.gz"
  skip_cleanup: true
  on:
    tags: true
