language: python
os:
  - linux
  - osx
python:
  - "3.6"
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install python3
install:
  - pip install tox
script:
  - tox
