language: python
python:
  - "3.7"
matrix:
  include:
    - os: linux
      dist: xenial
      sudo: true
    - language: generic
      os: osx
      before_install:
        - brew update
        - brew upgrade python
        - pip install -U pip
#        - pip3 install -U virtualenv
#        - python3 -m venv env
#        - source env/bin/activate
      sudo: true
install:
  - pip install tox
script:
  - tox
before_deploy:
  - pip install pipenv
  - pip install .[dev]
  - pyinstaller main.spec
  - tar -C dist/mocker -cvzf mocker-${TRAVIS_TAG}-${TRAVIS_OS_NAME}.tar.gz .
deploy:
  provider: releases
  api_key: ${GH_TOKEN}
  file: "mocker-${TRAVIS_TAG}-${TRAVIS_OS_NAME}.tar.gz"
  skip_cleanup: true
  on:
    tags: true
